function build_simulink()
% BUILD_SIMULINK  Dung mo hinh Simulink mo phong dong hoc Delta Robot.
%   Model 'delta_kinematics': Clock -> TrajGen (quy dao pick&place quintic)
%   -> IK -> theta[3]; FK verify TCP (sai so round-trip); Jacobian (condJ, mu).
%   Tai dung logic delta_ik/delta_fk/delta_jacobian (inline, codegen-safe).
%   Chay sim, xuat figs + so lieu. Bang chung deliverable.

sys = 'delta_kinematics';
here = fileparts(mfilename('fullpath'));
cd(here);
if ~exist('figs','dir'), mkdir figs; end
if ~exist('out','dir'),  mkdir out;  end
diary('out/simulink_build_log.txt'); diary on;
fprintf('=== BUILD SIMULINK: %s ===\n', sys);
fprintf('MATLAB %s\n', version);
fprintf('Simulink: %s\n', ver('simulink').Version);

% --- Tao model moi ---
if bdIsLoaded(sys), close_system(sys,0); end
f = fullfile(here,[sys '.slx']);
if exist(f,'file'), delete(f); end
new_system(sys); load_system(sys);

% --- Them block ---
add_block('simulink/Sources/Clock',            [sys '/Clock'],   'Position',[30 105 60 135]);
add_block('simulink/User-Defined Functions/MATLAB Function', [sys '/TrajGen'], 'Position',[110 88 190 142]);
add_block('simulink/User-Defined Functions/MATLAB Function', [sys '/IK'],      'Position',[240 88 320 142]);
add_block('simulink/User-Defined Functions/MATLAB Function', [sys '/FK'],      'Position',[380 33  460 95]);
add_block('simulink/User-Defined Functions/MATLAB Function', [sys '/Jac'],     'Position',[380 150 460 214]);
add_block('simulink/User-Defined Functions/MATLAB Function', [sys '/ErrNorm'], 'Position',[600 45 680 95]);
add_block('simulink/Math Operations/Sum',      [sys '/Perr'],    'Position',[520 50 545 100], 'Inputs','+-');
add_block('simulink/Math Operations/Gain',     [sys '/thetaDeg'],'Position',[380 250 460 290], 'Gain','180/pi');
add_block('simulink/User-Defined Functions/MATLAB Function', [sys '/JointVel'], 'Position',[380 320 460 384]);
add_block('simulink/Math Operations/Gain',     [sys '/omegaDeg'],'Position',[520 330 600 374], 'Gain','180/pi');
add_block('simulink/Signal Routing/Mux',       [sys '/Mux'],     'Position',[760 80 765 330], 'Inputs','6');
add_block('simulink/Sinks/To Workspace',       [sys '/logs'],    'Position',[820 190 900 230], ...
    'VariableName','simlog','SaveFormat','Timeseries','SampleTime','-1');
try, set_param([sys '/logs'],'LimitDataPoints','off'); catch, end
add_block('simulink/Sinks/Scope',              [sys '/Scope_theta'],'Position',[540 248 580 292]);
add_block('simulink/Sinks/Scope',              [sys '/Scope_omega'],'Position',[640 318 680 362]);

% --- Nap code cac MATLAB Function block (qua Stateflow chart) ---
rt = sfroot;
setChart(rt, [sys '/TrajGen'],  code_trajgen());
setChart(rt, [sys '/IK'],       code_ik());
setChart(rt, [sys '/FK'],       code_fk());
setChart(rt, [sys '/Jac'],      code_jac());
setChart(rt, [sys '/JointVel'], code_jvel());
setChart(rt, [sys '/ErrNorm'],  code_errnorm());

% Kiem tra so cong (port) da cap nhat theo chu ky ham
chk = {'TrajGen',1,2; 'IK',1,1; 'FK',1,1; 'Jac',2,2; 'JointVel',3,1; 'ErrNorm',1,1};
for k=1:size(chk,1)
    ph = get_param([sys '/' chk{k,1}],'PortHandles');
    fprintf('  %-8s in=%d out=%d (mong doi in=%d out=%d)\n', ...
        chk{k,1}, numel(ph.Inport), numel(ph.Outport), chk{k,2}, chk{k,3});
end

% --- Noi day ---
add_line(sys,'Clock/1','TrajGen/1','autorouting','on');
add_line(sys,'TrajGen/1','IK/1','autorouting','on');
add_line(sys,'TrajGen/1','Jac/1','autorouting','on');
add_line(sys,'TrajGen/1','Perr/1','autorouting','on');
add_line(sys,'TrajGen/1','Mux/1','autorouting','on');
add_line(sys,'TrajGen/1','JointVel/1','autorouting','on');
add_line(sys,'TrajGen/2','JointVel/3','autorouting','on');
add_line(sys,'IK/1','FK/1','autorouting','on');
add_line(sys,'IK/1','Jac/2','autorouting','on');
add_line(sys,'IK/1','thetaDeg/1','autorouting','on');
add_line(sys,'IK/1','JointVel/2','autorouting','on');
add_line(sys,'FK/1','Perr/2','autorouting','on');
add_line(sys,'Perr/1','ErrNorm/1','autorouting','on');
add_line(sys,'thetaDeg/1','Mux/2','autorouting','on');
add_line(sys,'thetaDeg/1','Scope_theta/1','autorouting','on');
add_line(sys,'JointVel/1','omegaDeg/1','autorouting','on');
add_line(sys,'omegaDeg/1','Mux/3','autorouting','on');
add_line(sys,'omegaDeg/1','Scope_omega/1','autorouting','on');
add_line(sys,'Jac/1','Mux/4','autorouting','on');
add_line(sys,'Jac/2','Mux/5','autorouting','on');
add_line(sys,'ErrNorm/1','Mux/6','autorouting','on');
add_line(sys,'Mux/1','logs/1','autorouting','on');

% --- Cau hinh solver ---
set_param(sys,'SolverType','Fixed-step','Solver','ode3','FixedStep','0.002','StopTime','1.2');

% --- Screenshot so do khoi ---
try
    set_param(sys,'ZoomFactor','FitSystem');
    print(['-s' sys], '-dpng', '-r120', 'figs/simulink_model.png');
    fprintf('Da luu figs/simulink_model.png\n');
catch ME
    fprintf('Screenshot loi: %s\n', ME.message);
end

save_system(sys);
fprintf('Da luu %s\n', f);

% --- Chay mo phong ---
fprintf('\n--- CHAY SIM (StopTime=1.2s, ode3, dt=0.002) ---\n');
simOut = sim(sys,'ReturnWorkspaceOutputs','on');
S = simOut.get('simlog');
t = S.Time;
Y = squeeze(S.Data);                 % [12 x N] hoac [N x 12]
if size(Y,1)==12 && size(Y,2)~=12, Y = Y.'; end   % -> N x 12
if size(Y,2)~=12
  error('Log width = %d (mong doi 12) -- Mux/To Workspace sai.', size(Y,2));
end
fprintf('Sim xong: %d buoc thoi gian, %d kenh\n', size(Y,1), size(Y,2));

Px=Y(:,1); Py=Y(:,2); Pz=Y(:,3);
THd=Y(:,4:6); OMd=Y(:,7:9); condJ=Y(:,10); mu=Y(:,11); errn=Y(:,12);

fprintf('\n--- KET QUA (doc tu SIM) ---\n');
for j=1:3
  fprintf('Khop %d: |theta|max=%.1f deg, |omega|max=%.1f deg/s (%.2f rpm)\n', ...
    j, max(abs(THd(:,j))), max(abs(OMd(:,j))), max(abs(OMd(:,j)))/6);
end
fprintf('Jacobian cond: max=%.3f, tb=%.3f ; goc truyen mu min=%.1f deg\n', ...
  max(condJ), mean(condJ), min(mu));
fprintf('Sai so round-trip FK(IK(P)) max = %.3e mm\n', max(errn));

% --- Figures ---
f1=figure('Visible','off','Position',[100 100 700 560]);
plot3(Px,Py,Pz,'b-','LineWidth',1.8); hold on; grid on;
plot3(Px(1),Py(1),Pz(1),'go','MarkerFaceColor','g');
plot3(Px(end),Py(end),Pz(end),'rs','MarkerFaceColor','r');
xlabel('x'); ylabel('y'); zlabel('z [mm]'); axis equal; view(0,0);
title('Quy dao TCP (SIMULINK sim)'); legend('quy dao','start','end');
saveas(f1,'figs/simulink_path.png');

f2=figure('Visible','off','Position',[100 100 900 700]);
subplot(2,1,1); plot(t,THd,'LineWidth',1.3); grid on; ylabel('\theta [deg]');
legend('\theta_1','\theta_2','\theta_3','Location','eastoutside'); title('Goc khop (Simulink)');
subplot(2,1,2); plot(t,OMd,'LineWidth',1.3); grid on; ylabel('\omega [deg/s]'); xlabel('t [s]');
legend('\omega_1','\omega_2','\omega_3','Location','eastoutside');
saveas(f2,'figs/simulink_joint_profiles.png');

f3=figure('Visible','off','Position',[100 100 800 600]);
subplot(2,1,1); plot(t,condJ,'LineWidth',1.4); grid on; ylabel('cond(J)'); title('Chi so Jacobian & goc truyen');
subplot(2,1,2); plot(t,mu,'LineWidth',1.4); grid on; ylabel('\mu [deg]'); xlabel('t [s]');
saveas(f3,'figs/simulink_jacobian.png');

f4=figure('Visible','off','Position',[100 100 800 400]);
semilogy(t,max(errn,1e-16),'m-','LineWidth',1.3); grid on;
xlabel('t [s]'); ylabel('|P - FK(IK(P))| [mm]'); title('Sai so round-trip FK(IK) tren Simulink');
saveas(f4,'figs/simulink_fkik_error.png');

save('out/simulink_results.mat','t','Y');
fprintf('Da luu 5 figs + out/simulink_results.mat\n');
fprintf('=== HOAN TAT ===\n');
diary off;
close_system(sys,1);
end

% ===================== helper =====================
function setChart(rt, pth, code)
ch = rt.find('-isa','Stateflow.EMChart','Path',pth);
ch.Script = code;
end

% ===================== code cac block =====================
function s = code_trajgen()
s = [ ...
"function [P, V] = trajgen(t)" newline ...
"%#codegen" newline ...
"W = [ 300 0 -1000; 300 0 -820; -300 0 -820; -300 0 -1000];" newline ...
"Tseg = [0.30 0.60 0.30];" newline ...
"Tend = sum(Tseg);" newline ...
"tt = mod(t, Tend);" newline ...
"if tt <= Tseg(1)" newline ...
"    k = 1; t0 = 0;" newline ...
"elseif tt <= Tseg(1)+Tseg(2)" newline ...
"    k = 2; t0 = Tseg(1);" newline ...
"else" newline ...
"    k = 3; t0 = Tseg(1)+Tseg(2);" newline ...
"end" newline ...
"Tk = Tseg(k);" newline ...
"s = (tt - t0)/Tk;" newline ...
"if s<0, s=0; end" newline ...
"if s>1, s=1; end" newline ...
"ss = 10*s^3 - 15*s^4 + 6*s^5;" newline ...
"ssd = (30*s^2 - 60*s^3 + 30*s^4)/Tk;" newline ...
"A = W(k,:); B = W(k+1,:);" newline ...
"Pv = A + ss*(B - A);" newline ...
"Vv = ssd*(B - A);" newline ...
"P = Pv(:); V = Vv(:);" newline ...
"end"];
s = char(join(s,''));
end

function s = code_jvel()
s = char(join([ ...
"function omega = jvel(P, theta, V)" newline ...
"%#codegen" newline ...
"R=347.0; r=120.6; L1=407.5;" newline ...
"phi=[-pi/2, pi/6, 5*pi/6];" newline ...
"omega=zeros(3,1);" newline ...
"for i=1:3" newline ...
"  c=cos(phi(i)); s=sin(phi(i)); ct=cos(theta(i)); st=sin(theta(i));" newline ...
"  Ei=[R*c+L1*ct*c; R*s+L1*ct*s; -L1*st];" newline ...
"  Pi=[P(1)+r*c; P(2)+r*s; P(3)];" newline ...
"  Li=Ei-Pi;" newline ...
"  vhat=[-st*c; -st*s; -ct];" newline ...
"  bden=L1*(Li'*vhat);" newline ...
"  if abs(bden)<1e-9" newline ...
"    omega(i)=0;" newline ...
"  else" newline ...
"    omega(i)=(Li'*V)/bden;" newline ...
"  end" newline ...
"end" newline ...
"end"],''));
end

function s = code_ik()
s = char(join([ ...
"function theta = ikfcn(P)" newline ...
"%#codegen" newline ...
"R=347.0; r=120.6; Rr=R-r; L1=407.5; L2=1000.0;" newline ...
"phi=[-pi/2, pi/6, 5*pi/6];" newline ...
"th_min=-pi/4; th_max=100*pi/180;" newline ...
"theta=zeros(3,1);" newline ...
"for i=1:3" newline ...
"  c=cos(phi(i)); s=sin(phi(i));" newline ...
"  u=(P(1)*c+P(2)*s)-Rr;" newline ...
"  w=-P(1)*s+P(2)*c;" newline ...
"  z=P(3);" newline ...
"  E=2*L1*z; F=-2*L1*u; G=L1^2+u^2+w^2+z^2-L2^2;" newline ...
"  rho=hypot(E,F);" newline ...
"  if rho<1e-12 || abs(G)>rho+1e-6" newline ...
"    theta(i)=NaN; continue;" newline ...
"  end" newline ...
"  psi=atan2(F,E);" newline ...
"  as=max(-1,min(1,-G/rho));" newline ...
"  b=asin(as);" newline ...
"  c1=atan2(sin(b-psi),cos(b-psi));" newline ...
"  c2=atan2(sin(pi-b-psi),cos(pi-b-psi));" newline ...
"  in1=(c1>=th_min && c1<=th_max);" newline ...
"  in2=(c2>=th_min && c2<=th_max);" newline ...
"  if in1 && in2" newline ...
"    theta(i)=min(c1,c2);" newline ...
"  elseif in1" newline ...
"    theta(i)=c1;" newline ...
"  elseif in2" newline ...
"    theta(i)=c2;" newline ...
"  else" newline ...
"    theta(i)=c1;" newline ...
"  end" newline ...
"end" newline ...
"end"],''));
end

function s = code_fk()
s = char(join([ ...
"function P = fkfcn(theta)" newline ...
"%#codegen" newline ...
"R=347.0; r=120.6; L1=407.5; L2=1000.0;" newline ...
"phi=[-pi/2, pi/6, 5*pi/6];" newline ...
"C=zeros(3,3);" newline ...
"for i=1:3" newline ...
"  c=cos(phi(i)); s=sin(phi(i)); ct=cos(theta(i)); st=sin(theta(i));" newline ...
"  Ex=R*c+L1*ct*c; Ey=R*s+L1*ct*s; Ez=-L1*st;" newline ...
"  C(i,:)=[Ex-r*c, Ey-r*s, Ez];" newline ...
"end" newline ...
"c1=C(1,:); c2=C(2,:); c3=C(3,:);" newline ...
"A=2*[c2-c1; c3-c1];" newline ...
"bb=[sum(c2.^2)-sum(c1.^2); sum(c3.^2)-sum(c1.^2)];" newline ...
"d=cross(A(1,:),A(2,:));" newline ...
"P=[NaN;NaN;NaN];" newline ...
"if norm(d)<1e-9, return; end" newline ...
"M=A*A';" newline ...
"P0=(A'*(M\bb))';" newline ...
"aa=dot(d,d); bq=2*dot(d,P0-c1); cq=dot(P0-c1,P0-c1)-L2^2;" newline ...
"disc=bq^2-4*aa*cq;" newline ...
"if disc<0" newline ...
"  if disc>-1e-6, disc=0; else, return; end" newline ...
"end" newline ...
"t1=(-bq+sqrt(disc))/(2*aa); t2=(-bq-sqrt(disc))/(2*aa);" newline ...
"Pa=P0+t1*d; Pb=P0+t2*d;" newline ...
"if Pa(3)<=Pb(3), Pv=Pa; else, Pv=Pb; end" newline ...
"P=Pv(:);" newline ...
"end"],''));
end

function s = code_jac()
s = char(join([ ...
"function [condJ, mu] = jfcn(P, theta)" newline ...
"%#codegen" newline ...
"R=347.0; r=120.6; L1=407.5;" newline ...
"phi=[-pi/2, pi/6, 5*pi/6];" newline ...
"A=zeros(3,3); bd=zeros(3,1); mus=zeros(3,1);" newline ...
"for i=1:3" newline ...
"  c=cos(phi(i)); s=sin(phi(i)); ct=cos(theta(i)); st=sin(theta(i));" newline ...
"  Bi=[R*c; R*s; 0];" newline ...
"  Ei=[R*c+L1*ct*c; R*s+L1*ct*s; -L1*st];" newline ...
"  Pi=[P(1)+r*c; P(2)+r*s; P(3)];" newline ...
"  Li=Ei-Pi;" newline ...
"  A(i,:)=Li';" newline ...
"  vhat=[-st*c; -st*s; -ct];" newline ...
"  bd(i)=L1*(Li'*vhat);" newline ...
"  bicep=Ei-Bi;" newline ...
"  cosb=(Li'*bicep)/(norm(Li)*norm(bicep));" newline ...
"  mus(i)=acos(max(-1,min(1,abs(cosb))))*180/pi;" newline ...
"end" newline ...
"B=diag(bd);" newline ...
"if abs(det(A))<1e-9" newline ...
"  condJ=1e6;" newline ...
"else" newline ...
"  Jf=A\B;" newline ...
"  condJ=cond(Jf);" newline ...
"end" newline ...
"mu=min(mus);" newline ...
"end"],''));
end

function s = code_errnorm()
s = char(join([ ...
"function e = errnorm(d)" newline ...
"%#codegen" newline ...
"e = norm(d);" newline ...
"end"],''));
end
